services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL_CLIENT: ${NEXT_PUBLIC_API_URL_CLIENT}
        NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    env_file: .env
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - flashcardsnet

networks:
  flashcardsnet:
    name: flashcardsnet
